services:
  api:
    depends_on:
      - postgres
    image: flanker1916/vehicles-management:latest
    volumes:
      - .:/usr/src/app
    env_file:
      - .env
    ports:
      - "5000:5000"
    pull_policy: always

  UI:
    depends_on:
      - api
    image: flanker1916/vehicle-management-ui:latest
    volumes:
      - .:/usr/src/app
    environment: 
      NODE_ENV: 'development' 
      REACT_APP_DEV_URL: http://localhost:5000/vehicles-api
    ports:
      - "3000:3000"
    pull_policy: always

  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: ${DATABASE_NAME}
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
    ports:
      - '5432:5432'
    volumes:
      - docker-nest-postgres:/var/lib/postgresql/data

volumes:
  docker-nest-postgres:
