services:
  api:
    depends_on:
      - postgres
    image: flanker1916/vehicles-management:latest
    volumes:
      - .:/usr/src/app
    env_file:
      - .env
    ports:
      - "5000:5000"

  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: ${DATABASE_NAME}
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
    ports:
      - '5432:5432'
    volumes:
      - docker-nest-postgres:/var/lib/postgresql/data

volumes:
  docker-nest-postgres:
